// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTVrDzX_hTjtS3fYY-9GqMLtmZkGXC1s',
    appId: '1:862845951191:web:9ed38b037455e3a8e16492',
    messagingSenderId: '862845951191',
    projectId: 'mobile-lab12-6f197',
    authDomain: 'mobile-lab12-6f197.firebaseapp.com',
    storageBucket: 'mobile-lab12-6f197.firebasestorage.app',
    measurementId: 'G-CSK2Y3CB5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0AQD4c8M9SZjzpEGaDsL4KqUOOIgA_Y',
    appId: '1:862845951191:android:6a4fc5dc934a3713e16492',
    messagingSenderId: '862845951191',
    projectId: 'mobile-lab12-6f197',
    storageBucket: 'mobile-lab12-6f197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhfMPiaU-rAQluhuAR7UkdbQ1Hixpp9Q',
    appId: '1:862845951191:ios:b959c24e0bfbf76ce16492',
    messagingSenderId: '862845951191',
    projectId: 'mobile-lab12-6f197',
    storageBucket: 'mobile-lab12-6f197.firebasestorage.app',
    iosBundleId: 'com.example.mobileLab13',
  );
}
